# Generated by Django 4.0.4 on 2022-04-26 12:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemistryThermal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Al', models.FloatField(default=0)),
                ('Cr', models.FloatField(default=0)),
                ('Cu', models.FloatField(default=0)),
                ('Mn', models.FloatField(default=0)),
                ('Mo', models.FloatField(default=0)),
                ('Nb', models.FloatField(default=0)),
                ('Ni', models.FloatField(default=0)),
                ('Si', models.FloatField(default=0)),
                ('Ti', models.FloatField(default=0)),
                ('V', models.FloatField(default=0)),
                ('W', models.FloatField(default=0)),
                ('C', models.FloatField(default=0)),
                ('N', models.FloatField(default=0)),
                ('P', models.FloatField(default=0)),
                ('S', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ThermalProps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cooling', models.BooleanField(default=False)),
                ('conductivity', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), size=None)),
                ('density', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), size=None)),
                ('specific_heat', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), size=None)),
                ('slug', models.SlugField(default='slug', max_length=100, unique=True)),
                ('chemistry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.chemistrythermal')),
            ],
        ),
    ]
