# Generated by Django 4.0.4 on 2022-04-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_chemistrythermal_thermalprops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thermalprops',
            name='slug',
        ),
    ]
