# Generated by Django 4.0.4 on 2022-04-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_remove_thermalprops_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistrythermal',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
