# Generated by Django 4.0.4 on 2022-05-18 14:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_alter_chemistrythermal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('steel_grade_name', models.CharField(max_length=100)),
                ('geometry', models.IntegerField()),
                ('thickness', models.FloatField()),
                ('initial_temperature', models.FloatField()),
                ('zones_number', models.IntegerField()),
                ('time_in_zones', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('temp_in_zones', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('coef_in_zones', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('temp_in_zones_bottom', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
                ('coef_in_zones_bottom', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
                ('thickness_layers', models.IntegerField()),
                ('time_step', models.FloatField()),
                ('result_zones', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
                ('result_time', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2)),
                ('result_temperature', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2)),
                ('result_change_rate', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2)),
                ('steel_grade_id_chemistry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.chemistrythermal')),
                ('steel_grade_id_prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.thermalprops')),
            ],
        ),
    ]
