# Generated by Django 4.0.4 on 2022-05-19 09:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_alter_calculatedresults_thickness_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatedresults',
            name='thickness_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
