# Generated by Django 4.0.4 on 2022-07-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_alter_calculatedresults_result_change_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WearProps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wear_value', models.FloatField()),
            ],
        ),
    ]
